---
- hosts: ec2-instance
  gather_facts: true
  sudo: true
  vars:
    ec2_instance:
      - name: "ec2_insance1"
        private_key_location: '/home/ubuntu/Ec2ansiblePlaceBook/VMock_Access_Key.pem'
        tags: { 'Name': 'VMock1' }
        ssh_user: "ubuntu"
      - name: "ec2_instance2"
        private_key_location: '/home/ubuntu/Ec2ansiblePlaceBook/VMock_Access_Key.pem'
        tags: { 'Name': 'VMock2' }
        ssh_user: "ubuntu"
  tasks:
     - name: Ec2 Step 1 | Launch instance
       ec2:
          key_name: "VMock_Access_Key"
          region: "us-west-1"
          group: "VMock_sg"
          instance_type: "t2.micro"
          image: "ami-b30356d3"
          vpc_subnet_id: "subnet-d5abbfbd"
          assign_public_ip: "true"
          instance_tags: "{{ item.tags }}"
          wait: true
          count: 1
       register: ec2
       with_items: ec2_instance
     - name: Wait for SSH
       wait_for:
          host: "{{ item['instances'][0]['public_ip'] }}"
          port: 22
          delay: 10
          timeout: 320
          state: started
       with_items: ec2.results

     - name: Wait a little longer
       pause: seconds=20

     - name: Add hosts group temporary inventory group with pem path
       add_host:
          hostname: "{{ item.public_ip }}"
          groups: dynamic_hosts
          ansible_ssh_private_key_file: '/home/ubuntu/Ec2ansiblePlaceBook/VMock_Access_Key.pem'
          ansible_ssh_user: "ubuntu"
       with_indexed_items: ec2_instances
- hosts: dynamic_hosts
  sudo: true
  tasks:
     - name: install apache2
       apt: name=apache2 update_cache=yes state=latest
