
- name: Ec2 Step 1 | Launch instance
  ec2:
     key_name: "VMock_Access_Key"
     region: "us-west-1"
     group: "VMock_sg"
     instance_type: "m1.small"
     image: "ami-e7035687"
     vpc_subnet_id: "subnet-29da2171"
     assign_public_ip: "yes"
     instance_tags: "{{ item.tags }}"
     wait: true
     count: 2
  register: ec2
  with_items: ec2.instances

- debug: var=item
  with_items: ec2.instances


- name: Ec2 Step 2 | Add instance to local host group
  local_action: lineinfile dest=inventory/ec2-instance regexp="{{item.public_ip}}" insertafter="[launched]" line="{{ item.public_ip }} ansible_ssh_private_key_file={{private_key_location}}"
  with_items: ec2.instances


- name: Ec2 Step 3 | Wait for the instances to boot by checking the ssh port
  wait_for: host={{item.public_ip}} port=22 delay=60 timeout=320 state=started
  with_items: ec2.instances
  tags: ec2-instance
